import type { LessonDocument } from "../lessonTypes";
import { deepCourseBlueprint } from "../deepCourseBlueprint";
import { HAND_AUTHORED_ALGEBRA } from "./handwritten/handAuthoredAlgebra";
import { HAND_AUTHORED_BIOMECHANICS } from "./handwritten/handAuthoredBiomechanics";
import { HAND_AUTHORED_CALCULUS } from "./handwritten/handAuthoredCalculus";
import { HAND_AUTHORED_COMMUNICATION_A } from "./handwritten/handAuthoredCommunicationA";
import { HAND_AUTHORED_COMMUNICATION_B } from "./handwritten/handAuthoredCommunicationB";
import { HAND_AUTHORED_COMMUNICATION_PAPER } from "./handwritten/handAuthoredCommunicationPaper";
import { HAND_AUTHORED_ENVIRONMENTAL } from "./handwritten/handAuthoredEnvironmental";
import { HAND_AUTHORED_GEOMETRY } from "./handwritten/handAuthoredGeometry";
import { HAND_AUTHORED_MULTIVAR } from "./handwritten/handAuthoredMultivar";
import { HAND_AUTHORED_PHYSICS_A } from "./handwritten/handAuthoredPhysicsA";
import { HAND_AUTHORED_PHYSICS_B } from "./handwritten/handAuthoredPhysicsB";
import { HAND_AUTHORED_STATCAST_A } from "./handwritten/handAuthoredStatcastA";
import { HAND_AUTHORED_STATCAST_B } from "./handwritten/handAuthoredStatcastB";
import { HAND_AUTHORED_STATCAST_METRICS_INTEGRATED } from "./handwritten/handAuthoredStatcastMetricsIntegrated";
import { HAND_AUTHORED_STATS_A } from "./handwritten/handAuthoredStatsA";
import { HAND_AUTHORED_STATS_B } from "./handwritten/handAuthoredStatsB";
import { HAND_AUTHORED_SCOREKEEPING } from "./handwritten/handAuthoredScorekeeping";
import { HAND_AUTHORED_BASEBALL_FINANCE } from "./handwritten/handAuthoredBaseballFinance";
import { HAND_AUTHORED_TRIG_PRECALC } from "./handwritten/handAuthoredTrigPrecalc";
import CMS_PUBLISHED_LESSONS from "../generated/cmsPublishedLessons.json";
import { ensureIntegrativeTitleSummatives, mergeUnitCloserSummatives } from "./unitCloserSummativeMerge";

const HAND_AUTHORED_MERGED: Record<string, LessonDocument> = {
  ...HAND_AUTHORED_ALGEBRA,
  ...HAND_AUTHORED_GEOMETRY,
  ...HAND_AUTHORED_TRIG_PRECALC,
  ...HAND_AUTHORED_CALCULUS,
  ...HAND_AUTHORED_MULTIVAR,
  ...HAND_AUTHORED_PHYSICS_A,
  ...HAND_AUTHORED_PHYSICS_B,
  ...HAND_AUTHORED_STATS_A,
  ...HAND_AUTHORED_STATS_B,
  ...HAND_AUTHORED_STATCAST_A,
  ...HAND_AUTHORED_STATCAST_B,
  ...HAND_AUTHORED_STATCAST_METRICS_INTEGRATED,
  ...HAND_AUTHORED_ENVIRONMENTAL,
  ...HAND_AUTHORED_BIOMECHANICS,
  ...HAND_AUTHORED_COMMUNICATION_A,
  ...HAND_AUTHORED_COMMUNICATION_B,
  ...HAND_AUTHORED_COMMUNICATION_PAPER,
  ...HAND_AUTHORED_SCOREKEEPING,
  ...HAND_AUTHORED_BASEBALL_FINANCE,
};

const lessonRuntimeBase = ensureIntegrativeTitleSummatives(mergeUnitCloserSummatives(HAND_AUTHORED_MERGED, deepCourseBlueprint));

const cmsLessonOverrides = CMS_PUBLISHED_LESSONS as Record<string, LessonDocument>;

/**
 * Hybrid bridge: CMS-published lessons can override authored runtime docs.
 * Source generated by `scripts/sync-cms-runtime.ts`.
 */
export const ALL_LESSONS: Record<string, LessonDocument> = {
  ...lessonRuntimeBase,
  ...cmsLessonOverrides,
};

export function getLessonByKey(key: string): LessonDocument {
  const doc = ALL_LESSONS[key];
  if (!doc) {
    throw new Error(`Missing hand-authored lesson for key ${key}`);
  }
  return doc;
}
